// Builds clean app data from https://github.com/vedicscriptures/bhagavad-gita
// Usage: node scripts/build-data.mjs <path-to-cloned-repo>
import fs from "node:fs";
import path from "node:path";

const src = process.argv[2];
if (!src) {
  console.error("Usage: node scripts/build-data.mjs <path-to-bhagavad-gita-repo>");
  process.exit(1);
}
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const outData = path.join(root, "src/data");
const outComm = path.join(root, "public/commentary");
const outVerse = path.join(root, "public/verse");
fs.mkdirSync(outVerse, { recursive: true });
fs.mkdirSync(outData, { recursive: true });
fs.mkdirSync(outComm, { recursive: true });

const FIELD_LABELS = {
  et: "English translation",
  ht: "Hindi translation",
  ec: "English commentary",
  hc: "Hindi commentary",
  sc: "Sanskrit commentary",
};

const isPlaceholder = (s) =>
  !s || s.trim().length < 5 || /did not comment on this/i.test(s);

// "2.47 Your right…" / "2.47. Let…" / "।।2.47।। कर्म…" -> strip leading verse number
const stripNum = (s) =>
  s
    .replace(/^\s*(।।)?\s*\d+\.\d+\.?\s*(।।)?\s*/, "")
    .replace(/\s+/g, " ")
    .trim();

// repo uses "." for avagraha in IAST (saṅgo.astv…) -> "'"
const fixTranslit = (s) =>
  s
    .replace(/\|\|\s*\d+-\d+\s*\|\|/g, "")
    .replace(/(\p{L})\.a/gu, "$1'")
    .replace(/\s*\.\s*\n/g, " |\n")
    .trim();

// Devanagari: drop trailing ||२-४७|| marker
const fixSanskrit = (s) => s.replace(/\|\|[०-९\d]+-[०-९\d]+\|\|/g, "॥").replace(/\|\|/g, "॥").replace(/\|/g, "।").trim();

const chapters = [];
for (let c = 1; c <= 18; c++) {
  const d = JSON.parse(fs.readFileSync(path.join(src, `chapter/bhagavadgita_chapter_${c}.json`), "utf8"));
  chapters.push({
    number: c,
    name: d.name,
    transliteration: d.transliteration,
    translation: d.translation,
    meaning: d.meaning?.en ?? "",
    summary: d.summary?.en ?? "",
    versesCount: d.verses_count,
  });
}

const verses = [];
const colophons = {};
const authors = {};
for (const ch of chapters) {
  const files = fs
    .readdirSync(path.join(src, "slok"))
    .filter((f) => f.startsWith(`bhagavadgita_chapter_${ch.number}_slok_`));
  for (const f of files) {
    const d = JSON.parse(fs.readFileSync(path.join(src, "slok", f), "utf8"));
    if (d.verse > ch.versesCount) {
      colophons[ch.number] = fixSanskrit(d.slok);
      continue;
    }
    const commentary = [];
    for (const [key, val] of Object.entries(d)) {
      if (!val || typeof val !== "object" || !val.author) continue;
      authors[key] = val.author;
      for (const [field, text] of Object.entries(val)) {
        if (field === "author" || isPlaceholder(text)) continue;
        commentary.push({ key, author: val.author, type: field, label: FIELD_LABELS[field] ?? field, text: stripNum(text) });
      }
    }
    const pick = (...keys) => {
      for (const k of keys) {
        const t = d[k]?.et;
        if (!isPlaceholder(t)) return stripNum(t);
      }
      return "";
    };
    const id = `${d.chapter}.${d.verse}`;
    verses.push({
      id,
      chapter: d.chapter,
      verse: d.verse,
      speaker: d.speaker,
      sanskrit: fixSanskrit(d.slok),
      transliteration: fixTranslit(d.transliteration),
      translation: pick("gambir", "siva", "adi", "san", "purohit", "prabhu"),
      translationBy: ["gambir", "siva", "adi", "san", "purohit", "prabhu"].map((k) => (!isPlaceholder(d[k]?.et) ? d[k].author : null)).find(Boolean),
      hindi: !isPlaceholder(d.tej?.ht) ? stripNum(d.tej.ht) : "",
    });
    fs.writeFileSync(path.join(outComm, `${id}.json`), JSON.stringify(commentary));
  }
}
verses.sort((a, b) => a.chapter - b.chapter || a.verse - b.verse);

fs.writeFileSync(path.join(outData, "verses.json"), JSON.stringify(verses));
for (const v of verses) fs.writeFileSync(path.join(outVerse, `${v.id}.json`), JSON.stringify(v));
fs.writeFileSync(path.join(outData, "chapters.json"), JSON.stringify(chapters));
fs.writeFileSync(path.join(outData, "authors.json"), JSON.stringify({ authors, colophons }, null, 1));

const SPEAKERS = { "श्रीभगवान्": "Krishna", "अर्जुन": "Arjuna", "सञ्जय": "Sanjaya", "धृतराष्ट्र": "Dhritarashtra" };
// Compact corpus for the LLM prompt: one line per verse
const corpus = [];
for (const ch of chapters) {
  corpus.push(`\n# Chapter ${ch.number}: ${ch.translation} (${ch.meaning})`);
  for (const v of verses.filter((x) => x.chapter === ch.number)) {
    corpus.push(`${v.id} [${SPEAKERS[v.speaker] ?? v.speaker}] ${v.translation}`);
  }
}
const corpusText = corpus.join("\n").trim();
fs.writeFileSync(path.join(outData, "corpus.txt"), corpusText);
fs.writeFileSync(path.join(outData, "corpus.ts"), `// Generated by scripts/build-data.mjs. Do not edit.\nconst corpus = ${JSON.stringify(corpusText)};\nexport default corpus;\n`);
console.log(`verses: ${verses.length}, colophons: ${Object.keys(colophons).length}, corpus chars: ${corpus.join("\n").length}`);
